name: bayesbridge_dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10 
  - numpy>=1.22
  - matplotlib>=3.0.0
  - pip
  - pip:
    - nox
    - sphinx
    - sphinx-rtd-theme
    - sphinx-design
    - sphinx-togglebutton
    - sphinx-copybutton
    - sphinxcontrib-mermaid
    - myst-nb
    - flake8
    - black
    - wheel
    - setuptools
    - cython
    - pytest
    - git+https://github.com/miili/pysurf96.git
